### ISSUE TITLE
Subscription switching - choose between attached sub schemes

### ISSUE THREAD

**Issue by franticpsyx** [Prospress/woocommerce-subscribe-all-the-things#12]
Here's something of a grander scale.

Add support for:
- Subscriptions schemes switching
- Changing the subscribed content of product types such as Bundles and Composites (may require integration on their side)
- Cart subscription management (and switching)

I am not sure if all these WC Subscriptions features need to be ported to SAtT at this time, or if at all.

If WC Subscriptions ever absorbs the SAtT workflow, all these things will be easier to port, but my guess is that we'll need quite a bit of infrastracture in WC Subs to decouple all the subscription switching logic from the Grouped/Variable sub types.

**Comment by franticpsyx** [comment]
@thenbrent CC'ing you on this one - do you think we might be able to "just" hook into WCS and enable sub switching for subscription plans/schemes attached to products via SATT?

**Comment by thenbrent** [comment]
> do you think we might be able to "just" hook into WCS and enable sub switching for subscription plans/schemes attached to products via SATT?

Hopefully! We did a bit of work with Kathy to make sure there were enough hooks in place for 3rd party code to decouple switching from Grouped/Variable products. She wanted to make Name Your Price Simple Subscriptions switchable (so that customers could change the amount they pay without cancelling/reactivating the subscription). 

For details of all the hooks added (meaning the hooks you'll probably want to use), I think these are all the relevant PRs/Issues are:

* https://github.com/Prospress/woocommerce-subscriptions/issues/687
* https://github.com/Prospress/woocommerce-subscriptions/issues/883
* https://github.com/Prospress/woocommerce-subscriptions/pull/954
* https://github.com/Prospress/woocommerce-subscriptions/pull/987
* https://github.com/Prospress/woocommerce-subscriptions/issues/981
* https://github.com/Prospress/woocommerce-subscriptions/pull/1095/

**Comment by franticpsyx** [comment]
:+1:

**Comment by alexchristiansen** [comment]
Hi @franticpsyx 
I am currently very close to having a perfect setup with your SATT. 
Though only "issue" left is the switch-subscription. 
I tried to see @thenbrent photos - though 404 on those atm. 

Could you elaborate on the situation with switching? Did you guys get it to work?

**Comment by franticpsyx** [comment]
Hey @alexchristiansen - we haven't started working on this just yet. Currently the priority is to resolve some pending issues with the supported product types + to add support for the variable type. This is something we definitely want to look into, but at the moment we have not ETA.

**Comment by kevibethink** [comment]
Hey @franticpsyx - I just wanted to follow up on this as a few months have gone by and it's a feature I desperately need too. SATT solved a lot of issues I had with Woo Subscriptions and in my mind is how Woo Subscriptions should have been setup in the first place to allow single orders or subscriptions of the same product like Subscriptio does. 

I had been using the hacky way of setting a daily subscritpion that expired after 1 day for single purchases, but that meant the subscription feed in the admin got cluttered with what were essentially single orders. 

Grouping the products wouldn't work either because we need inventory management which that killed, but it seems if I can get subscription switching to work with SATT I'll have all the boxes checked for the client's needs. If you have no timeline for it do you think it'd be possible for me to do with hooks? I tried the links @thenbrent had posted, but they're all 404'd now. Any help would be appreciated. Thanks!

**Comment by franticpsyx** [comment]
Hey @kevibethink - what product type are you looking into?

I have been working on some Composite / Bundle features that should make subscription switching easier in SATT, but it might be easier to do it if you are working with Simple / Variable products.

Regardless, we'll need to approach this step by step, starting with the simpler product types and move gradually from there.

Unfortunately there is no immediate plan to start working on this, since I have a backlog of issues I would like to clear in the next couple weeks.

**Comment by kevibethink** [comment]
Thanks for the quick response @franticpsyx 

I have a simple product that can be purchased once or subscribed to weekly, bi-weekly, or monthly. I basically need a switch subscription button on the customer account page that will allow them to switch the subscription frequency at any time.

**Comment by everlykyle** [comment]
Voicing love for this plugin extension (thank you!) and echoing the need for switching - both delivery frequency and products.

For simplicity for the customer, a subscription could be thought of as a basket. They can change how often the basket comes to them and what is in the basket each time.

For now, I am using Gravity Forms on a universal subscription product to allow customers to change what is in their basket as a work around (see intro page [here](https://goeverly.com/subscribe) and form [here](https://goeverly.com/product/plan/)). Excited to improve this experience down the line with SAtT with switching. 

Would switching include the ability to change what is in a subscription's basket? Or just delivery frequency? Thanks!

**Comment by WillBrubaker** [comment]
@franticpsyx @thenbrent - got a FB DM about this. A friend of a friend type thing - looks like there might be some demand for it so.... 👍  :)

**Comment by franticpsyx** [comment]
Hey @WillBrubaker @everlykyle 

While we do have plans for subscription switching, we will be looking at this at a product level first - considering the complexity of Bundles/Composites this is not going to be an easy task. Once this gets sorted, we will be looking into cart subscriptions switching, however I don't expect such a feature to be ready any time soon.

SATT development has been frozen during the last few weeks since we are working on a backlog of issues and new release features on projects that SATT depends on (Subscriptions, Bundles, Composites). 

Development should start again later in Q4 16, but with WC 2.7 on the horizon it will be hard (if not impossible) to work on new SATT features.

**Comment by GAPP99** [comment]
Hey guys, any update with this? I'm in dire need of this exact feature, as the Mix 'n Match products is dynamic, and changes every 2nd month. I would happily donate a bit for this feature.

**Comment by franticpsyx** [comment]
@GAPP99 

We will be coming back to SATT after WC 2.7 is released. As mentioned in https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/57#issuecomment-263045473 

>WC 2.7 requires all extensions in the Subscriptions/SATT ecosystem to be updated in order to be compatible, so at the moment features development in SATT is in freeze mode as we look into / implement the required changes.

**Comment by GAPP99** [comment]
@franticpsyx Quick question. Is it possible to manually modify the Mix 'n Match subscriptions with this thread in mind? I tried adding other products, and copy/pasted the meta values, which seemed to work. Only thing is that it doesn't treat the modified products as Mix 'n Match. 

This is a screenshot of Orders, where you can see the first original order was 1 product and 7 mixed: http://prntscr.com/ducwe1

Here's a screenshot of what meta values I changed inside the actual subscription: http://prntscr.com/ducy52

Looking forward to your response.

**Comment by franticpsyx** [comment]
@GAPP99 It's a bit more complex that that because Subscriptions and Orders are not the same thing. Essentially what we need is a way to "bulk edit" multiple Subscriptions purchased in some context, e.g.

- a Mix and Match product,
- a Product Bundle, or
- an entire cart.

**Comment by GAPP99** [comment]
@franticpsyx Okay, that's understandable naturally. I know there will be a lot of new features coming up with the new WC, and I can wait with the bulk editing. For now though, I'd love to be able to do these things myself in any way possible.

What I have been thinking would be just to add a form to "My Account > Subscriptions", and then the customers wanting to change the Mix 'n Match products could just submit their selection to me, and I would go ahead and change it manually.

Is there any way to manually modify the subscriptions?

**Comment by franticpsyx** [comment]
>Is there any way to manually modify the subscriptions?

You would need to manually cancel any active Subscriptions. Then perhaps you could try to modify the active SATT scheme ID of order item meta when ordering again? But still, that would require you to write some code and would be a clumsy way to do it.

**Comment by GAPP99** [comment]
@franticpsyx Oh boy. My problem is, that we're launching our food subscription service this monday, and it would be a huge mess if the customers can't change their Mix 'n Match products inside the subscription in some way or another.

So I guess I have two options, since I can't wait till the new release comes out:
1. I'm then either looking at setting up a manual temporary setup, which I can do myself. Naturally the code for this would be from a developer.
2. Or hiring a developer to modify the whole process, so the customer is able to change their subscription products without going through the checkout process. 

Do you have any recommendations for me, or something I should be careful about when finding a developer?

**Comment by franticpsyx** [comment]
>Do you have any recommendations for me, or something I should be careful about when finding a developer?

Your biggest concern, in my opinion, should be the fact that you are going to production/live with infrastructure that's labelled as experimental/beta (SATT). Being dependent on a non-commercial/beta plugin means that, ultimately, you will need to be prepared:

- to deal with any issues that arise from its use over time,
- to maintain/upgrade the entire plugin yourself should it get forked, abandoned or absorbed into another free/commercial project in the future.

Regardless of which developer/agency you choose, they should be willing to accept this (and provide an offer/quote that takes these facts into account).

**Comment by seb86** [comment]
@GAPP99 Hi.

> Or hiring a developer to modify the whole process, so the customer is able to change their subscription products without going through the checkout process.

I have experimented with change items in a subscription before. It's not that easy but is doable. However, I have only tried for simple subscriptions. I'm not sure how different it is for Mix and Match products.

As @franticpsyx has said this plugin is still experimental and there are a lot of things that will change once 2.7 of WooCommerce is released. Your best option in my opinion would be to fork the plugin and maintain your own code base if you are going to go live with your setup.

As for your customers, to change their subscription without checkout it would be best for them to select the items for the container on the product page again, only as they already have a subscription the button will change from "Add to Cart" to "Change Subscription". That way the data is passed correctly without additional hard work.

That's just one idea but if you want to discuss more I am happy to chat privatley should you wish.

**Comment by pprotschka** [comment]
@GAPP99 what a coincidence...also doing a food subscription site. Also using SATT. i develop myself but not on a professional/full time basis. perhaps we can come together and share the costs.

**Comment by seb86** [comment]
@pprotschka Interesting. 2 birds, one stone. You would both have to agree to the same specs.

**Comment by GAPP99** [comment]
@seb86 Interesting. I'm definitely interested in this. Do you have a skype username I can contact you on?

@pprotschka Lovely, so let's discuss how we can be of help to each other and possibly share the costs if we can find an acceptable compromise. Do you have a skype username I can contact you on, as well?

**Comment by seb86** [comment]
@GAPP99 @pprotschka My Skype is sebsstudio

**Comment by GAPP99** [comment]
@pprotschka I'm awaiting your response. You can add me on Skype: danstah8

**Comment by alexchristiansen** [comment]
@GAPP99 / @seb86 / @pprotschka 
I am very interested as well. 
Using SATT for a subscription service whereas we would like to offer the opportunity of switching between SATT subscriptions. 
I am interested in a potential split of cost as well. 
I am happy to talk more about this. Either alexander (at) organicbasics.com or skypeid: alexander.cgroup

Looking forward to chat. 

@franticpsyx while we are at it - can you elaborate on what aspects of WC 2.7 you are "afraid" of in a SATT aspect?

**Comment by pprotschka** [comment]
i added you guys on skype. perhaps we can talk more in a group chat there.

**Comment by seb86** [comment]
@alexchristiansen That is great to hear. I think we are going to have an interesting group conversation. Also, I think @franticpsyx is referring to this article that was released today. https://woocommerce.wordpress.com/2017/01/17/deprecation-in-woocommerce-core/

I also suggest all three of you [send me your ideas and specs](https://sebastiendumont.com/contact-me/) individually and I will look over them and see where I can find a common ground in the project that is shared equally for it all to work out so I can see in advanced from a development point of view.

Then we just need to establish a time to communicate because we have different time zones. I can do this coming Thursday at 4PM GMT+1.

[Please confirm](https://calendly.com/sebastiendumont/15min/01-17-2017) and lets try to keep the conversation within 45 minutes so each of you will have 10 minutes each pitching your idea and I will provide my feedback and then at the end we have 15 minutes to discuss between each other to marry the majority of your ideas together.

I hope that is agreeable with you all.

**Comment by GAPP99** [comment]
Whenever Alex accepts the invite on Skype, I'll start a group chat for all 4 of us, then we can discuss the project. 

Thank you, Seb.

**Comment by seb86** [comment]
@GAPP99 Please confirm that you read this.

> Then we just need to establish a time to communicate because we have different time zones. **I can do this coming Thursday at 4PM GMT+1.**

**Comment by franticpsyx** [comment]
Hey guys -- locking this for now as the discussion is really not adding anything to the Issue.

**Comment by franticpsyx** [comment]
Closing. Will re-open as we start tackling the tasks in https://github.com/Prospress/woocommerce-subscribe-all-the-things/wiki/Roadmap

**Comment by franticpsyx** [comment]
Also this is too general. We plan to work on switching for different things: built-in types, carts, custom types. Each will be tackled separately and with different priority.
