### ISSUE TITLE
Compatibility with "Advanced Pricing" or "YITH WooCommerce Role Based Prices"

### ISSUE THREAD

**Issue by philschoefer** [Prospress/woocommerce-subscribe-all-the-things#130]
Hi guys,

I just wanted to report that there is an issue with he plugin with a lot of "Role Based" pricing plugins that hook into the same "woocommerce_get_price" hook, specifically with Subscription Discounts.

Essentially the "Discount" entered for subscriptions is completely ignored once a plugin is installed that hooks into the same "woocommerce_get_price" hook as SATT does. It seems like "filter_price" depends on some parameter being set a certain way for the discount to actually be outputted.

I can still see the discount in the SCHEMA, so something must be overwriting it.

**Comment by franticpsyx** [comment]
Hey @philschoefer 

SATT hooks into most price filters at priority `0` in order to be able to **overwrite** the price when the "Override product" option is selected under **Product Data > Subscriptions > Subscriptions Options > Price**.

So if a callback attached later does something similar, or is poorly coded (e.g. unnecessarily overwrites the passed value with a the "raw" prop value), then the SATT discount could be "lost".

There is not much we can do about it -- for the most part, it's up to plugin authors to _mutate_ instead of _overwrite_ the passed price value.

Hope this helps!

**Comment by philschoefer** [comment]
Thank you! Yes that helps.
