### ISSUE TITLE
Recurring Totals Show 0 at Checkout

### ISSUE THREAD

**Issue by spruceupsoapco** [Prospress/woocommerce-subscribe-all-the-things#142]
When i select a subscription and then attempt to check out with that subscriptions the recurring billing details show as zero.
![image](https://user-images.githubusercontent.com/29690021/27516654-0d703dc6-598c-11e7-8644-b98498cf3962.png)

**Comment by spruceupsoapco** [comment]
Please note this is a composite product

**Comment by franticpsyx** [comment]
@spruceupsoapco Can you please share WC/CP/SATT version numbers?

**Comment by spruceupsoapco** [comment]
SATT = 2.0
WC = 3.0.9
CP = 3.10.1

It seems that the recurring totals show on check out when you use the price override but it does not show total products recurring totals if you choose to  inherit the product prices of the products that make up the composite product. When you inherit the product prices the cp price override is auto set to 0 which is why i am assuming the recurring totals show 0 in the snap shot.

**Comment by franticpsyx** [comment]
@spruceupsoapco Wasn't able to replicate any issue here.

"Override" only affects the base composite price, and child/component prices are not modified.
"Inherit" affects both the base composite price and child/component prices in the same way (same discount applied to all). Example:

https://cl.ly/3T3e3M0Y3B2N

See https://cl.ly/2U2g3K3b0D2q -- assuming a base price of $100:

- The weekly scheme applies a $50 discount to the base price and child prices are the same.
- The daily scheme applies a 50% discount to everything.

Everything works correctly in the cart, too.

I assume that the products you have added to your Composite don't have any subscription schemes attached. Composite Products only works with SATT if you attach subscription schemes at Composite level, e.g. in order to offer a product kit on a recurring basis.
