### ISSUE TITLE
Still shows double subscription period

### ISSUE THREAD

**Issue by zielo** [Prospress/woocommerce-subscribe-all-the-things#176]
I`ve downgraded to WC 2.6.14 and I`m using latest SATT version, however I get the same error - the subscription on cart and check out pages is doubled. See below:

![28119872-fffa78f0-671e-11e7-9255-c60895e12dc9](https://user-images.githubusercontent.com/6492978/28283424-612596f8-6b36-11e7-9018-174a198d7b4e.PNG)

![28119931-30e49b12-671f-11e7-9805-8ee4285a0caa](https://user-images.githubusercontent.com/6492978/28283443-6a643080-6b36-11e7-8ed4-41ef69381224.PNG)

**Comment by franticpsyx** [comment]
@zielo See https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/178

If this happens with the latest version of WCS, SATT and WC, we are happy to investigate. Unfortunately the limited amount of resources we have available for SATT makes it difficult to keep supporting older WC/WCS versions.

Thanks for understanding!

**Comment by zielo** [comment]
Strange, because I reported the same bug twice. Previously you replied that this is a compatibility issue and closed the thread. You wrote that WC 3+ is not compatible with latest SATT. Even though I was using the latest versions of WCS, SATT and WC.  Guess what, it`s not compatible with any versions, either older or the newest. What does it take to recognize it as a bug??

**Comment by franticpsyx** [comment]
@zielo 

- WC 3.0+ is not compatible with SATT version 1
- WC 3.0+ is supported by SATT version 2, which is about to be released.
- SATT version 2 will not support WC 2.6.

This will be fixed in SATT v2, which will support WC 3.0 only. We will not be releasing another v1 version, so if this bug is present when using SATT v1 in combination with WC 2.6, then your only option will be to update to WC 3.0+ and SATT v2.

I would recommend waiting for the SATT v2.0 beta to be tagged and then test with WC 3.0/3.1. If the issue persists, feel free to comment or open a new issue.

Thanks!

**Comment by zielo** [comment]
@franticpsyx thanks for clarifying, also great job with the new v.2 release! Thank you! Now I`m actually using WC 3.1.1, and WS 2.2.7 together with the latest SATT beta release, but the problem still persist. I`m not really sure if this is even SATT issue, or Mix and Match products plug-in, which I doubt, but still I don`t see how others don`t have problems with it, as it really looks a major one...

**Comment by franticpsyx** [comment]
Replicated and patched in `master`.

**Comment by zielo** [comment]
@franticpsyx Thanks a bunch! It works as a charm now!
