### ISSUE TITLE
Is the SATT v2 out now?

### ISSUE THREAD

**Issue by aljohnrey** [Prospress/woocommerce-subscribe-all-the-things#182]

**Comment by willgorham** [comment]
2.0 Beta release is here: https://github.com/Prospress/woocommerce-subscribe-all-the-things/releases/tag/2.0.0-beta.1

Not a production release yet though

**Comment by aljohnrey** [comment]
When will be the release of the production?

**Comment by seb86** [comment]
Once the beta has been tested well enough and very few reports come back to say something is broken. We don't want to rush the project plus our time is limited. Do you have any issues currently? If so please open a new ticket with a detailed report. Thank you.

**Comment by aljohnrey** [comment]
I downloaded the beta version of the plugin but I am having this error on the product page the "Add to cart" button became "Sign up" and the design, is that really is?
![test](https://user-images.githubusercontent.com/28753362/28553973-3a70f428-7129-11e7-80dd-8d2098e7775d.png)

**Comment by aljohnrey** [comment]
Hi guys

Any upadate on my issue? 

I would really appreciate your quick response to this matter

**Comment by seb86** [comment]
@aljohnrey As I said, please open a new issue. This is unrelated to the issue you started. Also please provide your WooCommerce System Status Report by copying and pasting it in the new issue.

As to what you have pointed out already the "Add to Cart" button changes to "Sign Up" because the product is now a subscription.

I also advise that you [read the support](https://github.com/Prospress/woocommerce-subscribe-all-the-things#support) section in the readme file.

Thank you.

**Comment by franticpsyx** [comment]
Looks like a theme issue, @aljohnrey -- might be a good idea to work with a developer to resolve that, as there is not much we can do on our side.

For customizations I can totally recommend @seb86 who is experienced with both WCS and SATT -- not sure if he is available at the moment though - feel free to send him a DM.
