### ISSUE TITLE
Woocommerce "Subscription Data" tab is missing.

### ISSUE THREAD

**Issue by eliv3n** [Prospress/woocommerce-subscribe-all-the-things#183]
![screen shot 2017-07-24 at 12 13 58 pm](https://user-images.githubusercontent.com/7813781/28508022-1d40444a-706a-11e7-99a4-40075b372831.png)
 

Deactivated all the plugins, using "Avada" theme latest version.

**Comment by eliv3n** [comment]
anyone duplicated the same issue? 
I have this issue after updating to the latest version of woocommerce subscription plugin.

**Comment by eliv3n** [comment]
i find the issue within the CSS
![screen shot 2017-07-24 at 1 32 13 pm](https://user-images.githubusercontent.com/7813781/28509719-97e90b1c-7076-11e7-9fe2-193391875ce6.png)

any shortcut or snippets to overwrite the current class 'postbox closed' ?

**Comment by thenbrent** [comment]
@eliv3n that doesn't look like an issue specific to _Subscribe All the Things_, it looks like a _theme_ conflict with the main Subscriptions plugin.

This repository is for issues with _Subscribe All the Things_, not the main _Subscriptions_ plugin or any other plugin sold via WooCommerce.com.

To get help debugging your issue, please submit a ticket to WooCommerce.com support system here: http://woocommerce.com/my-account/create-a-ticket/

So that we can help as quickly as possible, please include on the WooCmmerce.com ticket:

* temporary admin credentials to login to your site so we can confirm
* a copy of your System Status report
