### ISSUE TITLE
Commercial use

### ISSUE THREAD

**Issue by spouellet** [Prospress/woocommerce-subscribe-all-the-things#188]
Hello. I'm really interesting in your plugin, since it's the only one I've found to do what I want to do on my website 
I'm really interested to test it and send you comments...but I wanna be sure it will not affect my website before.. I'm doing +100 transactions per days, so wanna be sure everything will work fine.
Just have 8 products.
Do the 2.0 version is ready for commercial use? Do you recommend it?

Thanks

**Comment by sambomcd** [comment]
Hi Spouellet. I am using 2.0 on a live site, and have not had any issues so far. **HOWEVER:** The dev team do not officially recommend doing this. Plus the plugin is not officially supported, so if you do run into problems that could be an issue for you. I think if you are able to set up a test environment and try the plugin out for a while first, that would be a good idea. Obviously my site and reliance on this plugin will be different to yours!

**Comment by franticpsyx** [comment]
@spouellet there's a lot of information [here](https://github.com/Prospress/woocommerce-subscribe-all-the-things/wiki) to help you decide.

>  I'm doing +100 transactions per days, so wanna be sure everything will work fine.

No piece of software can be guaranteed to to work flawlessly during its entire lifetime, unless it has zero dependencies. Right now, SATT is probably as stable as the best WooCommerce extensions out there. However, because SATT works on top of WooCommerce and Subscriptions, there's a high chance something _might_ break in the future -- for example if you perform a major update without testing everything first. 

In general, a _software issue_ might be due to:

- A misunderstanding of how the software works.
- A dependency/environment issue.
- A bug in (someone else's or your own) code.

To minimize the exposure of your business on _software issues_, you basically have the following options (not mutually exclusive):

- Hire a software expert to keep an eye on everything (including your server), investigate issues for you and get in touch with software authors to get them patched.
- Pay an annual/monthly fee to software authors who offer a support service and be directly supported by their teams. In this case, their support teams will do most of the investigation for you, and you will be able to get fixes/patches quickly -- however, you will also have to do some work yourself (e.g. keep in touch with your host when server issues come up, be aware of best practices when updating, keep backups, test updates, do some investigation work, etc).

With this in mind, the most important factor to consider is that SATT does **not include a paid support option**. You can, of course, report issues here -- however, if we can't replicate the reported issue in our testing environment, in most cases we will not be able to keep looking. In contrast, a "paid" support team would:

- log into your store to replicate the issue, 
- collect data, and
- eventually let you know whether your issue is due to a server problem, a bug in (third-party or own) code (e.g. a payment gateway) or a misconfiguration. 

This means that you will either need to do this work yourself, or hire an expert to help you out (either permanently or when things go wrong).

Hope this helps you decide!
