### ISSUE TITLE
Schemes are still active even when the product type has changed

### ISSUE THREAD

**Issue by seb86** [Prospress/woocommerce-subscribe-all-the-things#201]
So I wanted to see what would happen if I created a simple product and added 2 subscription schemes. 1 Montly and 1 Yearly. I publish the product and see the options available. This is fine and works as it should.

However, when I change the product type from "Simple product" to "Simple subscription", set the billing to yearly, enter the higher price and then "Update" the product... now when viewing the product page both subscription schemes are still there only the billing periods are both yearly.

When going back to edit the product the product type has gone back to "Simple product". This is not right.

What should happen is as you change the product type you are asked if you are sure you want to change product type and in doing so you will loose your subscription schemes set. If accepted the schemes are removed and the product type selected is the product type that it should be when the product is updated again.

I just thought this might be a useful user test for you guys and get your thoughts on this issue.

**Comment by franticpsyx** [comment]
> When going back to edit the product the product type has gone back to "Simple product". This is not right.

Hey @seb86 :)

There's no code in SATT that would modify the product type, or affect it in any way.

There could be issues with lingering WCS meta when switching from a subscription-type to a core type. It's probably a good idea to take a look at this scenario and delete any WCS meta left over so ensure SATT can work without problems.

cc @thenbrent

**Comment by franticpsyx** [comment]
> There could be issues with lingering WCS meta when switching from a subscription-type to a core type.

Re the opposite, the desired behavior is that SATT should not work with non-supported types. If it does, it's likely a bug caused by `is_type()` used instead of `get_type() ===`, as I believe subscription types return `true` when using the former to check against `simple`/`variable`. Definitely need to have another look though.

**Comment by franticpsyx** [comment]
@seb86 I have followed your exact steps and delved into the code but couldn't replicate any issues. The code includes a bunch of safeguards to prevent issues with lingering meta -- there's also a bunch of type-checking based on `get_type` rather than `is_type`, which I feared (more below).

I didn't see any weird behavior with lingering product types either. We are not setting or changing the product type anywhere.

I was able to uncover a case where `is_type` was called, but this can't have the implications you describe: https://github.com/Prospress/woocommerce-subscribe-all-the-things/commit/2dede17f6a57629945391186a3f7465051fc1607 

I have moved on and tagged v2.0.1 which is long overdue. If you manage to replicate this with all plugins / custom code disabled let me know.
