### ISSUE TITLE
Billing Cycle not showing for composite products

### ISSUE THREAD

**Issue by lmartins** [Prospress/woocommerce-subscribe-all-the-things#213]
Hi,

I'm trying to get a composite product to allow for subscriptions, problem is the prices at the end don't include the subscription cycle along with the prices:

https://cl.ly/2M3G1A2v1020
This test was done running the Twenty Seventeen theme.

Anything I can do to get around this?

**Comment by franticpsyx** [comment]
Hey @lmartins -- I'm not able to replicate: https://cl.ly/150K023D3F2E

Please make sure that you are running the latest versions of everything (WC, WCS, CP, SATT).

If the issue persists, I would suggest disabling all other plugins and checking again -- if the issue is resolved, enable plugins one by one until you find the culprit.

**Comment by lmartins** [comment]
Hi @franticpsyx thanks for the feedback. I'll dig this further. When I saw the notice about the use of this plugin on production sites I just assumed it wasn't fully baked yet, but I'll try finding what's causing the issue in this case. Thank you for checking it.
