### ISSUE TITLE
Subscribe all things not functioning with custom product boxes

### ISSUE THREAD

**Issue by justinnettl** [Prospress/woocommerce-subscribe-all-the-things#215]
Hi there,
Im using [custom product boxes by Wisdmlab](https://wisdmlabs.com/assorted-bundles-woocommerce-custom-product-boxes-plugin/)s, alongside [Subscribe All things ](https://github.com/Prospress/woocommerce-subscribe-all-the-things), however when in the Cart, the subscription options are not there as Subscribe all things is not recognising the "Custom Product Box" product type as something that is subscribable.

Is it possible to make the subscribe all things plugin recognize custom product boxes as a product available for subscriptions?

Cheers, looking forward to feedback
Justin

**Comment by franticpsyx** [comment]
Hey @justinnettl 

In addition to the Simple and Variable types built into WooCommerce, SATT is compatible with:

- Product Bundles
- Composite Products
- Mix and Match Products

I'm not sure if one of these product types would be suitable for you, but we have no plans to support Custom Product Boxes. Please remember that every decision to support a third-party plugin creates a long-term maintenance commitment for us, which means we can only add support for a plugin/extension if there is significant demand for it. 

Note that it's rarely possible to make two plugin "play nice" with each other by writing code on one side -- so a decision to introduce compatibility between two plugins usually requires opening a channel of communication between two sides and keeping it open for the foreseeable future. It's not a decision to be taken lightly :)

If the developers of Custom Product Boxes are interested in adding SATT compatibility on their side and need some help finding their way around our code, we'll be happy to help them out.

**Comment by seb86** [comment]
Isn't Custom Product Boxes similar to Mix and Match Products?

**Comment by easilyamused** [comment]
We were able to get this to work once, but it was a big pain in the neck.
In order to get SATT to work, we had to add the to the array of supported
product types.

We should have added this as a function and overridden the filter.

public function get_supported_product_types() {

return apply_filters( 'wcsatt_supported_product_types', array( 'simple',
'variable', 'variation', 'mix-and-match', 'bundle', 'composite',
'wdm_bundle_product','wcpb' ) );
}

We also had to add some CSS to the admin to make that tab show on the
single product view in the admin.

We were able to get this to work but there is no real way of changing your
subscription without canceling and starting a new one.

We also had to do tons of work to get the Custom Product Boxes to remember
what your subscription was last time incase you wanted to change it from
month to month.

Long story short, it is doable but was way more work then we wanted and now
we can’t upgrade Custom Product Box plugin with out hours of extra work.



-- 
James Tryon, Founder

Easily Amused, Inc.

http://EasilyAmusedInc.com <http://easilyamusedinc.com/>



e: james@easilyamusedinc.com

t: @jamestryon

From: Manos Psychogyiopoulos <notifications@github.com>
<notifications@github.com>
Reply: Prospress/woocommerce-subscribe-all-the-things
<reply@reply.github.com>
<reply@reply.github.com>
Date: October 13, 2017 at 8:53:41 AM
To: Prospress/woocommerce-subscribe-all-the-things
<woocommerce-subscribe-all-the-things@noreply.github.com>
<woocommerce-subscribe-all-the-things@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
<subscribed@noreply.github.com>
Subject:  Re: [Prospress/woocommerce-subscribe-all-the-things] Subscribe
all things not functioning with custom product boxes (#215)

Hey @justinnettl <https://github.com/justinnettl>

In addition to the Simple and Variable types built into WooCommerce, SATT
is compatible with:

   - Product Bundles
   - Composite Products
   - Mix and Match Products

I'm not sure if one of these product types would be suitable for you, but
we have no plans to support Custom Product Boxes. Please remember that
every decision to support a third-party plugin creates a long-term
maintenance commitment for us, which means we can only add support for a
plugin/extension if there is significant demand for it.

Note that it's rarely possible to make two plugin "play nice" with each
other by writing code on one side -- so a decision to introduce
compatibility between two plugins usually requires opening a channel of
communication between two sides and keeping it open for the foreseeable
future. It's not a decision to be taken lightly :)

If the developers of Custom Product Boxes are interested in adding SATT
compatibility on their side and need some help finding their way around our
code, we'll be happy to help them out.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/215#issuecomment-336444196>,
or mute the thread
