### ISSUE TITLE
Subscription option not showing on product page when using individual item pricing

### ISSUE THREAD

**Issue by alexghattas** [Prospress/woocommerce-subscribe-all-the-things#230]
First off, great plugin that has helped me a ton with the mix and match and subscription plugins.

A bug I have found that seems to be a little weird in terms of UX, is when you selecting individual item pricing for a mix and matched product, the subscription option does not show on the product page and shows on the cart page. Versus when you charge a flat fee for the mix and match product, the subscription options display on the product page. Is there any way to show the subscription options on the product page for individual item pricing?

Thanks!

**Comment by franticpsyx** [comment]
Hey @alexghattas 

The client-side script powering the Mix and Match extension is quite limited, making it hard to write a well-functioning integration that we can maintain in the long run.

Instead of Mix and Match, you could try to use Product Bundles in combination with [this](https://github.com/somewherewarm/woocommerce-product-bundles-min-max-items) little mini-extension. This will give you the best of Product Bundles + Mix and Match. 

However, note that this mini-extension is unsupported at the moment. We are currently exploring some options that will allow us to provide support for mini-extensions like **PB: Min/Max Items** via WooCommerce.com, and/or merge the functionality of similar extensions such as Product Bundles and Mix and Match to focus on developing new features. Nothing is final just yet, but in any case Product Bundles and its small ecosystem will be staying around, which makes it a safer choice for new projects.

For the record, Mix and Match is built by @helgatheviking and myself, so this is not a case of me/us trying to pitch a different extension/product than the one you already have.
