### ISSUE TITLE
Subscribe to Cart functionality not triggering

### ISSUE THREAD

**Issue by giulianorapoz** [Prospress/woocommerce-subscribe-all-the-things#290]
Hi there,

Having issues with the "Subscribe to cart" functionality not updating the cart total and not triggering the recurring billing when checking out (Paypal).

I have tested the scenario just using the WooCommerce Subscriptions functionality (enabling a simple subscription per product) and the end2end scenario flow works.

However enabling"Subscribe to cart" functionality (which is the part I need) doesn't appear to do anything in terms of updating the cart or calculating the recurring cost?

Image of cart:
https://imgur.com/a/HYw40

Site:
http://proteinandpantryshop.azurewebsites.net/basket/

Any help would be very much so appreciated!

Kind Regards,
Giuliano

**Comment by giulianorapoz** [comment]
Anyone got ideas why the Subscribe to cart functionality may not be triggering and updating the cart total?

**Comment by franticpsyx** [comment]
Hey @giulianorapoz I haven't been able to look at your site yet, but locally v2.0.1 works without issues for me, so I'd recommend checking to see if this might be due to a theme or plugin conflict.

<ol>
<li>Temporarily switch back to a default WordPress theme (or Storefront). If this resolves the issue, then please bring this to the attention of your theme author.</li>
<li>If the issue persists, then disable all other plugins except for WooCommerce and extension. If this fixes the issue, then slowly re-enable plugins until you find the one that triggers it.</li>
</ol>

**Comment by giulianorapoz** [comment]
Hi @franticpsyx thanks for replying!

I figured it out. It seems like old cookies had been stored and the site had been cached. Once cleared, the functionality works as expected.

Will close the issue.
