### ISSUE TITLE
Forced subscriptions and subscribe entire cart

### ISSUE THREAD

**Issue by cturnbull** [Prospress/woocommerce-subscribe-all-the-things#298]
- Make a simple product. Nothing fancy.
- In the subscriptions tab, select force subscription.
- Don't add subscription options to the product.
- Instead, in the WC -> subscriptions settings, add some cart subscription options e.g. every month, every two months. 

Note: for simplicity's sake, I want to configure my site so each initial order can only have a single subscription associated with it, i.e. one or many different products with different quantities etc, but the same billing interval. This is why I love the idea of subscribing to the entire cart, not individual cart lines. If the customer wants to make a subscription with a different billing interval, then she will just have to make a new order.

This would simplify our administrative process. It would also prevent screwups with free shipping; for example, when a customer orders a monthly subscription and an every two month subscription in the same order and qualifies for free shipping on the initial order, on the third month you'd have two renewals at the same time, but one or both of them may not qualify for free shipping even though grouped together, with a higher order total, they would have qualified. It's a pain to deal with and hard to explain to customers.

Anyway, what happens:

- The product view and product category view of the product is pretty much identical to a simple product without subscription options. This is fine. I want the customer to subscribe only on the shopping cart, and they won't be selecting subscription options at this stage.
- When navigating to the shopping cart, I'm greeted with: "<product> is only available with a subscription plan. Please choose a plan to proceed.", in a big red error message. 
- I am invited to choose a subscription plan, the wording of which makes it sound like it's optional, i.e. I'm also given the option to say no thanks.
- If I select a cart subscription option other than no thanks, I still get the same error message.
- Interestingly, If I select no thanks, I'm still able to proceed to the checkout to make a one-off payment, even though force subscription is selected.

What I'd expect in this scenario:

1. If there is no opportunity to one-off purchase any of the products in the cart at the time, there should be no option to proceed to checkout / complete a purchase, until a subscription plan is selected.
2. There should be no error message about selecting a subscription plan if a cart subscription option has been selected
3. A customer should of course be notified that a subscription plan is required, but it seems rather in-your-face with a big red error message, as if they've done something wrong. I would instead expect the customer to now be invited to select a plan, as that's required. Or allow a default cart subscription to be selected, or both these things.

**Comment by franticpsyx** [comment]
Hey @cturnbull -- thanks for the detailed report!

This is an interesting one: **Force subscription** is only designed to do _something_ in combination with the defined **product-level** schemes. It was never designed to work in conjunction with cart-level schemes, which are optional by definition.

You _can_ force a cart level scheme to be applied via filters, assuming there is one at least on offer -- but you can't do this at product level, and not using the **Force subscription** setting.

From what I can tell, you:

* want to only make that product available on a recurring basis only; and
* customers are expected to choose a cart-level subscription to purchase it.

At the moment, there's no flow built into SATT logic to support this. This explains why the behavior you see doesn't make sense -- you expect that option to do something, which makes sense because you can save it, but that option is not designed or tested to work in this use case.

This is clearly bad design on our part, and I agree that this needs to be addressed, but first we'll need to review what the expected flow/behavior should be.

* If **Force subscription** is designed to work with product-level schemes only, then it shouldn't be possible to enable it without adding some subscription schemes.
* If it's meant to be used with ANY scheme, no matter where it comes from, then you shouldn't be able to purchase it without choosing a cart scheme.

Generally speaking, if we accept that the second behavior is the "right" one, then:

* You should be able to tell that the product is only available on a recurring basis from the single-product page already, or even just by looking at it in the catalog.
* If a cart contains at least 1 product that needs to be force-subscribed, you shouldn't be seeing the "No thanks" option, and a cart scheme should be applied by default.

Admittedly this would be a cool feature if we had intended it to work like you describe.

One problem with this, however, is that although product-level schemes may coexist in the same store with cart-level schemes, you are only offered cart subscription options if your cart doesn't contain any items that have product-level schemes. In other words, cart-level schemes aren't designed to override OR complement product-level schemes in the same cart.

This means that if **Force Subscription** is used to create an expectation that a product without product-level schemes should be purchased by choosing a cart-level subscription scheme, THEN there's a weird situation created if you add that product to the cart along with a product that has product-level schemes: 

You'd be offered no cart-level schemes and essentially you'd be "stuck" there, as you:

* have a product in the cart that requires choosing a subscription scheme;
* the product has no schemes of its own;
* the cart offers no schemes because another product with product-level schemes is in the cart as well.

The only solution to this would be to allow cart + product level schemes to co-exist on different cart items, basically by "moving" cart-level schemes to cart-item-level.

Which then creates _another_ problem: By doing so, you would allow different cart items with cart-level schemes to be purchased with different billing schedules in the same cart, which isn't really what "subscribing to cart" is about.

So -- summing up: The feature you propose can only work if that particular product (**Force Subscription**  enabled and no product-level schemes defined) is not allowed to co-exist in the cart with products that have product-level schemes. While this _can_ be enforced it would be a rather clunky workaround and would require coming up with a nice, meaningful message that would explain to a customer why they aren't allowed to add something to their carts.

Hopefully these thoughts will help us work on this soon -- right now I don't think we can fit this into the 2.1 cycle, so IMO the best decision right now would be to prevent **Force Subscription** from being enabled unless there's at least 1 product-level scheme.

Thanks a ton for the feedback!

**Comment by franticpsyx** [comment]
> IMO the best decision right now would be to prevent Force Subscription from being enabled unless there's at least 1 product-level scheme

As discussed, no last minute changes here. The entire codebase so far is written on the premise that product + cart subscription scheme settings cannot interact/interfere with each other. This is far from saying that the current implementation prevents a developer from customizing the default behavior -- quite the contrary.

The product-level Force Subscription setting is not the way to Force cart-level subscription options.

Note that https://github.com/Prospress/woocommerce-subscribe-all-the-things/commit/d2679e141fefc8954623e14adf79ad27f635084c prevents the user from seeing any general subscription-related options unless there's at least 1 scheme defined. This will ensure that others don't get caught up trying to make SATT do something it's not designed to.

Thanks again for the feedback!
