### ISSUE TITLE
Simple Product on Sale with Subscription Options

### ISSUE THREAD

**Issue by seb86** [Prospress/woocommerce-subscribe-all-the-things#30]
@thenbrent and @franticpsyx I noticed that if a simple product that is on sale has subscription options, the price on the subscriptions are still taking a percentage of the regular price not the sale price.

![Simple Product on Sale with Subscription Options](https://cldup.com/QrsyTxoCOg.png)

Should it not inherit the sale price of the product when it is on sale and provide a discount percentage from that?

**Comment by franticpsyx** [comment]
See https://github.com/Prospress/woocommerce-subscribe-to-all-the-things/blob/master/includes/class-wcsatt-schemes.php#L159

The filter can be used to apply the percentage on top of the sale price :)

**Comment by seb86** [comment]
@franticpsyx OK but the average user who does not know how to code is not going to know that filter is available so should we not then add a new option to deterin the result of that filter?

If not then at least put some kind of message in the product panel to notify the user what happens. What do you think @thenbrent ?

**Comment by thenbrent** [comment]
@franticpsyx what was the thinking behind using the regular price by default instead of the sale price?

I'm inclined to agree with @seb86 that the default behaviour should be to honour the `$price` value so that sale prices and other filters applied to the product's price are honoured before applying the SATT discount.

**Comment by franticpsyx** [comment]
>what was the thinking behind using the regular price by default instead of the sale price

It was based on user feedback from the Product Bundles extension, where (oddly) I had quite a few requests to have discounts applied on top of regular prices to avoid sale prices propagating into bundles.

Similarly in this case, my thinking was that people may temporarily want to have a sale price applied for a limited time when doing a one-off purchase, without affecting the subscription scheme prices (always based on the regular price).

**Comment by thenbrent** [comment]
Hrm, yeah I thought it may have been related to Bundles where it makes sense... the second use case of temporary sales also makes sense.

I think we can probably preserve the current behaviour and instead of changing it, try to avoid the confusion by being explicit about what will be discounted by changing the `Discount %` label to say `Discount Regular Price (%)` (e.g. https://cloudup.com/cfnw7hrOGET)
