### ISSUE TITLE
Gateway Timeout Error

### ISSUE THREAD

**Issue by margaretrivermarketing** [Prospress/woocommerce-subscribe-all-the-things#320]
When my customers get to the Cart Subscription, where they select the 6 month subscription frequency, it comes up with 504 Gateway Timeout. 
I am going through the process of elimination to figure out where the error is originating and am desperate for some guidance. 
The cart subscription was working fine yesterday and then in the afternoon the error started. Any ideas?
![screen shot 2018-06-25 at 8 51 56 pm](https://user-images.githubusercontent.com/38829889/41851193-b48fea64-78b9-11e8-9574-139106cc9be3.png)

**Comment by franticpsyx** [comment]
> The cart subscription was working fine yesterday and then in the afternoon the error started. Any ideas

Hey @margaretrivermarketing -- if you didn't change anything in SATT, then this indicates a possible Gateway issue. Did you update any plugins recently? Generally speaking, this may be caused by either:

<ul>
<li>custom code introduced recently;</li>
<li>a conflict with your theme; or</li>
<li>a conflict with a plugin.</li>
</ul>

Here's how we usually address this type of issue:

<ol>
<li>Temporarily switch back to a default WordPress theme (or Storefront). If this resolves the issue, then please bring this to the attention of your theme author.</li>
<li>If the issue persists, then disable all other plugins except for WooCommerce, WCS and SATT (and your gateway, of course). If this fixes the issue, then slowly re-enable plugins until you find the one that triggers it.</li>
</ol>

If the issue still persists, then it might be a good idea to investigate the Gateway side of things. Contacting the awesome support team at Prospress might be a good idea once you have ruled out everything else.

PS: Would love to visit Margaret River one day!

**Comment by franticpsyx** [comment]
### Cause ###

See 4f794399a0aa1673204688537a1d03ec97d5ceca

When using `indexOf` we need to check for `-1`, not boolean.
