### ISSUE TITLE
Compatibility with new Woocommerce Multi Currency plugin

### ISSUE THREAD

**Issue by afeistenauer** [Prospress/woocommerce-subscribe-all-the-things#325]
Hi,

I tried out the new woocommerce multi currency plugin today: https://woocommerce.com/products/multi-currency/
Turns out that subscription prices of simple products with subscribe all the things are not correctly handled.
Where could I start adding support for this?

**Comment by thenbrent** [comment]
Hi @afeistenauer does it work with standard subscription products? Like Simple Subscription or Variable Subscriptions?

Depending on the answer to that, the best approach to proceed will be different. :)

**Comment by afeistenauer** [comment]
Hi @thenbrent.
According to documentation it should work with Subscriptions:
"WooCommerce Multi-currency is tested with the standard product types, Subscriptions, and Bookings."

Just tested it with a simple subscription product and it works fine.

**Comment by thenbrent** [comment]
@afeistenauer thanks for letting us know. I suspect what will need to happen is that the Multicurrency Plugin will need to use another filter and/or manually support another product type. Hopefully, this won't be too hard given it already supports simple subscriptions, but you never know.

Have you created a ticket via the [WooCommerce.com Marketplace Ticket form](https://woocommerce.com/my-account/marketplace-ticket-form/) to ask the Tiv.net about adding support for SATT product types? If not, please do that and we can take it from there somehow (I think we may be in a shared Slack with Tiv.net developers, so can potentially liaise with them on it there).

**Comment by afeistenauer** [comment]
@thenbrent that's a great suggestion.
I've sent them a request just now. Development of their plugin has been active since public release, so I hope they will jump on this as well.

**Comment by tivnet** [comment]
@afeistenauer Got the ticket. Thanks for letting me know.
@thenbrent @franticpsyx I will check it out.

**Comment by tivnet** [comment]
@afeistenauer @thenbrent @franticpsyx Added a filter in Version 1.4.0. Smoke-tested. 

P.S. Was a bit confused with subscription "inherited from the price". Expected it to be the price divided by the number of payments?

**Comment by franticpsyx** [comment]
@tivnet that would have been an installment 😄 but yeah it's often a bit vague what a "subscription" is -- for example you might be offered to pay $100 for a publication and receive a copy every month for a year, or set up a subscription and pay $5 per month for X years. That would be more aligned to your idea of a subscription, but then what if you want to get a bag of coffee beans every month? You'd pay the same price, or almost the same, as what you'd pay if you'd buy the bag of beans once.

**Comment by franticpsyx** [comment]
So anything we need to add here? SATT code is written in a way that shouldn't introduce any compatibility issues -- it's basically `get_price` filters, but the only "weird thing" about it is that the filters are attached with priority `0`, to allow overriding prices while giving an opportunity to other plugins to work as intended. In retrospect, this could have been a negative priority number as well, but in principle if you are using price filters to convert between currencies (which I'd guess), then you shouldn't have any issues.

If you are loading a different price for each currency, like how Aelia does it, then I'm pretty sure you'd need to follow a similar approach as SATT and override prices as early as possible -- even earlier than SATT. I don't know how Aelia does it, but I have the impression they are filtering price meta (messing with data stores) which might be more performant but maybe harder in terms of maintenance/compatibility in the long run.

**Comment by franticpsyx** [comment]
> override prices as early as possible -- even earlier than SATT

After chatting with @tivnet it seems this isn't possible, which I had forgotten, because we override prices at that point by using the WC price getters in 'edit' context. So any modifications by third-parties that happened at an earlier priority would be "lost".

This was a known limitation when the code was written -- in fact there's no better approach when working with such an event-based system.

This is a prime example of communication being the only way to resolve these issues. Fortunately for Gregory (and us), there's the `wcsatt_subscription_scheme_prices`, but IMO the ideal approach is to slowly fine-tune our priorities to ensure that whoever must hook earlier _can_ hook earlier.

Gregory suggests that `0` might be too late and I agree. When I wrote the code I assumed that most people would hook in at priority `10`, which is the WP default, but since SATT needs to override prices completely AND give an opportunity to other (discount/multi-currency) plugins to modify prices, I think we should eventually use an earlier priority (probably in SATT 3.0).
