### ISSUE TITLE
X% Off + Free Shipping Capability?

### ISSUE THREAD

**Issue by tommytompkins** [Prospress/woocommerce-subscribe-all-the-things#340]
Hello,

I'm currently using the Woocommerce Subscriptions plugin by itself with subscription variations to achieve a one-time purchase option for product along with "Deliver every X weeks" options.  I'm currently offering 10% off + Free Shipping for subscribing instead of purchasing one-time.  The way that I'm achieving a "one-time purchase" option is through a 1-day subscription on the product variation that expires after 1 day.  It's pretty clunky and not a very elegant solution. Hence, the reason why I'm looking at Subscribe-All-The-Things.

I recently found your plugin and was hoping to use this to replace my subscription variations.  However, I'm not seeing an easy way to accomplish the "free shipping" requirement of my subscriptions. Currently, I'm able to select a shipping class on each subscription variation and I'm selecting a "free shipping" class that I created in Woocommerce which ultimately gives the customer free shipping when they checkout without having to enter any promo codes. 

Is there an easy way to accomplish what I'm looking for now that I'm just not thinking of?  Or can we add a new feature to this plugin that would allow me to select a new shipping class with each subscription option?

**Comment by franticpsyx** [comment]
Hey @tommytompkins -- working with subscription schemes instead of variations does have some limitations like this one: Since you don't have a different product (variation) ID that helps you identify the chosen billing schedule, business logic that relies on this (such as shipping classes) doesn't carry on to the "SATT way".

To address limitations like this one, you will essentially need to use a different set of tools to accomplish the same thing.

[WooCommerce Conditional Shipping and Payments](https://woocommerce.com/products/conditional-shipping-and-payments/#) is an interesting extension to look into for situations like the one you describe, and although it currently doesn't include any Subscriptions-specific features, we are planning to introduce an integration with WCS that will allow you to define subscriptions-related conditions for cart items in Shipping Method restrictions, e.g. recurring total, chosen billing period, etc.

At the moment there is no ready-made solution for what you describe. However, if the above sounds interesting we can definitely keep you in the loop here and let you know when support for Subscriptions is built into Conditional Shipping and Payments (planned within the next few weeks).
