### ISSUE TITLE
Recurring Product Discount error - calculating 20 as 200

### ISSUE THREAD

**Issue by Cenay** [Prospress/woocommerce-subscribe-all-the-things#351]
Let me see if I can explain this in writing. 

Client is meal prep company, that sells prep'd meals on a weekly subscription. They offer discounts and coupon codes a lot. They were attempting to add a new coupon code to allow $20 off each week of a subscription (with no renewal limits). 

They added the coupon as:
Discount type: Recurring Product Discount
Coupon amount: 20
Coupon expiry date: 2018-10-07
Active for x payments: Unlimited payments 

*all this is in the video explanation below*

When the first customer entered that coupon code, it discounted 100% of the cart amount. 

We did some testing, and changing the "20" to "2" did give us a $20 discount, however, that's not correct. Can you please review? Do we have a setting wrong? A rounding issue? (Again, everything is in the video)

[Full video explanation on Screencast](https://www.screencast.com/t/I7ijY7kE69iu)

**Environment:**
WordPress 4.9.8
WooCommerce 3.4.5
WooCommerce Subscriptions 2.3.2
WooCommerce Subscribe All The Things 2.1.1

WooCommerce System Status available at this Gist
https://gist.github.com/Cenay/b39b5935a7fb8d80b7e2aa96ac8288e9

**Comment by thenbrent** [comment]
Hi @Cenay, thanks for the great video & issue description!

The **_Recurring Product Discount_** is a _product_ coupon, so it discounts each product in the cart. Because the item in the cart is priced at $10.99, a $20 coupon reduces it's amount entirely to $0. Product coupons are also multiplied by the quantity of the product in the cart. That's why changing the coupon amount to $2 discounts the cart the desired $20.

This is the expected behaviour of **_Recurring Product Discount_** coupons because it matches the behaviour of WooCommerce core's **_Fixed product discount_** coupons.

While it's possible to use the **Limit usage to X items** setting to reduce the coupon to be used for just one item, e.g. http://pic.pros.pr/c575346439d4, that still won't get you the consistent $20 discount in all cases. Only some.

What you would need for this use case is a new **_Recurring Cart Discount_** that matches the behaviour of WooCommerce's **_Fixed Cart Discount_**. That's not on our Roadmap as yet and I didn't see an [open feature request](http://ideas.woocommerce.com/forums/133476-woocommerce?query=recurring%20cart%20discount) for this functionality with enough votes to get it on our roadmap.

That means the only solution for now is to use the _Recurring Product % Discount_ approach or get custom code to implement a  **_Recurring Cart Discount_**. Sorry I don't have better options!

**Comment by Cenay** [comment]
Appreciate your clear notes and reasoning. I will admit, that I am disappointed. This client pretty clear on what they want to do, and I thought I had found the perfect solution for them. =(

**Comment by thenbrent** [comment]
Completely understand @Cenay, and I'm sorry I couldn't be the bearer of better news. Unfortunately, with over [200 feature requests](http://ideas.woocommerce.com/forums/133476-woocommerce/category/146472-extension-woocommerce-subscriptions), and thousands of use cases, we disappoint more than I would like.

One day your client will be to create a recurring cart discount coupon with Subscriptions. Whether that day is in the next few weeks or next few years will just depend on whether you need to wait until we write the code for it, or your client needs this functionality enough to justify funding development of it as a customisation.
