### ISSUE TITLE
One Time Shipping not honoured for Variable Product with Subscription Scheme

### ISSUE THREAD

**Issue by dss-rtm** [Prospress/woocommerce-subscribe-all-the-things#357]
I've tried to find the cause of the error and think it is with your plugin.

I have all my SATT subscription products to be set to "one time shipping" (then free there-after) but when there are any **variable SATT subscription products** in the cart, either alone or with other items, it makes the cart charge recurring shipping for that product, even though all products have been set to use "one time shipping"

As a test... 

Add a **Variable Product with SATT Subscription** to your cart and it will make the cart calculate and display charges for recurring shipping.
https://dentalsafetysolutions.com/shop/safety-products/protective-apparel/dupont-tyvek-400-125s-disposable-coveralls-elastic-wrists-25qty/

This scenario only happens to **Variable Products with SATT Subscription**

add a **Simple Product with SATT Subscription** to your cart (it does not charge recurring shipping in the cart)
https://dentalsafetysolutions.com/shop/safety-products/face-protection/face-it-disposable-face-shields-with-drape-50-box/

Or add a **Variable Product** to your cart (they will not charge recurring shipping)
https://dentalsafetysolutions.com/shop/safety-products/3m-6000-half-facepiece-reusable-respirator/

Again, I apologize if this error does not originate with your plugin. But if it does, I thought you should know. 
Thanks
Randall

**Comment by thenbrent** [comment]
Hi @dss-rtm thanks for the excellent report. I have reproduced this now and can confirm, it is a bug. 

@franticpsyx I've looked into this and found:

1. SATT is correctly setting the [`_subscription_one_time_shipping` meta data](https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/master/includes/admin/meta-boxes/class-wcs-att-meta-box-product-data.php#L415)
1. that is all that's required for `WC_Subscriptions_Product::needs_one_time_shipping()` to treat a variable subscription product as a one time shipping product; however, 
1. when `WC_Subscriptions_Product::needs_one_time_shipping()` is called via `WC_Subscriptions_Cart::set_cart_shipping_packages()`, it:
    1. passed the variation object in `$cart_item['data']`, and then 
    1. `WC_Subscriptions_Product::needs_one_time_shipping()` instantiates the variable product, because it needs to check the variable product data, not the variation data; however
    1. the variable product instance instantiated there does not identify as a subscription product

Thoughts on the best way to solve this?

There's quite a few options, like:

1. explicitly filtering `'woocommerce_subscriptions_product_needs_one_time_shipping'` in SATT to handle this case; or
1. mapping the variable product to be a subscription based on the cart item somehow; or
1. loosening the `is_subscription()` requirement in `WC_Subscriptions_Product::needs_one_time_shipping()` and instead, only checking the meta data.

None of those seem ideal though.

**Comment by franticpsyx** [comment]
Thanks for the details @thenbrent . Got a few tasks on the Analysis queue now that will need to be included in the next fix release. Will not be able to get to them before next week though!

**Comment by franticpsyx** [comment]
@thenbrent Generally, SATT sets the "subscription state" of a product: 

* on the instance itself;
* in cart (item) session data -- https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/master/includes/class-wcs-att-cart.php#L80
* in order item meta

...and we rely on restoring the object/instance state from whatever source we have available.

One issue with this architecture is that any piece of (usually third-party) code may create new product instances in "enclosed contexts" and fail to restore the subscription state from a "source" object, either because such an object can't be reached (e.g. not passed into a filter) or because it's necessary to work with a parent/container instance -- as in this case here.

The best solution in such cases is to find a cheap way to restore the "subscription state" of the new object, which requires a way to associate it with:

* a "source" instance; or
* a cart/order item.

The problem here is that we have:

`$product = self::maybe_get_product_instance( $product->get_parent_id() )` 

followed by a call to:

`self::is_subscription()`.

This will always break SATT and we need to make sure that WCS avoids such patterns when possible, as we did when we mildly refactored WCS to ensure that `is_subscription()` never receives a product ID when a source product object is available.

Possible solutions:

1. 

Add some code in WCS to make variation instances in the cart inherit such meta from their parent, probably on session load. Then functions like `needs_one_time_shipping` should check the source object (variation) first, and only fall back to the parent if the meta we're looking for doesn't exist.

As an analogy, when you call `get_category_ids()` on a variation object, you'll always get an empty array. IMO that's wrong: WC doesn't do anything to ensure variation data stores read this data from parent products (for perf reasons), and doesn't even fall back to the parent at runtime. WCS falls back to the parent, without checking the child.

Not an ideal approach.

2.

Filter the result of `maybe_get_product_instance` and let SATT restore the subscription state from a "source" object. To do this, we'd need to pass the "source" (variation) object into `maybe_get_product_instance`. 

Not ideal either.

3.

Loosen the `is_subscription` requirement in `get_meta`. 

This doesn't feel right to me in general, but it's the right thing to do in _some_ cases. Here, WCS is calling `needs_one_time_shipping` knowing that it's working with subscription objects already, so it doesn't feel right/optimal to call `is_subscription` again.

To let SATT do its work, WCS needs to explicitly avoid calling `is_subscription` on objects that get temporarily created at runtime -- and this is a good example.

One way to do this would be to:

* add an extra argument to `get_meta` that disables the `is_subscription` check;
* slowly refactor the WCS codebase to call `get_meta` without checking for `is_subscription` when this isn't necessary.

By doing this, we'll be optimizing WCS (and SATT) at runtime -- right now `woocommerce_is_subscription` is running an excessive number of times in every request, mostly without any real need.

As we discussed recently on Slack, WC + WCS + SATT trigger an enormous amount of filters, and `woocommerce_is_subscription` is easily one of the over-utilized ones.

Not an ideal approach but feels like the most logical one to me, as calling `is_subscription` in every `get_meta` call is excessive.

**Comment by dss-rtm** [comment]
Hi @thenbrent & @franticpsyx ,  thanks for acknowledging this bug and commenting on possible solutions. I was wondering if this bug was slated to be fixed before the end of this year?
Thanks for all your work on this awesome plugin... do you think it will one day make it into Woocommerce Subscriptions?

**Comment by franticpsyx** [comment]
Hey @dss-rtm 

> I was wondering if this bug was slated to be fixed before the end of this year?

Probably yes. It needs some work on the WCS side, which is why it's been left in "pending" state for this long.

> do you think it will one day make it into Woocommerce Subscriptions?

For as long as we've been developing SATT, we've been investigating and evaluating whether the entire project can become the "new standard" for WooCommerce Subscriptions. Today we have a much clearer idea of how store owners and developers use both WCS and SATT -- and through this process of understanding, we recognized that there is technically no feasible way to replace subscription product types with SATT's "schemes/plans".

Including both approaches in WC Subscriptions is something we evaluated, as well, but rejected the idea as potentially very confusing for new store owners.

Today, we are convinced that:

1. Subscription-type products are here to stay. 
2. Both approaches are needed and always will be, as they serve different audiences and use cases.

This naturally begs the question "What's the future of SATT now?".

We want to keep moving the project forward to help store owners do more (and succeed) with WooCommerce. Make it easier for WCS users to find SATT. Assist store owners and developers when they reach out to us for help -- which is something we've never been able to handle as well as we'd like. 

But to do all of this, we'll need to be able to put resources into SATT on a daily basis. We'll need to have access to the same customer-driven decision-making tools and processes we're using to improve our paid extensions.

We've come to the conclusion that the best way to do this is to commercialize the project. We're still not sure how soon, or how this will happen, but we're working on it :)

**Comment by dss-rtm** [comment]
@franticpsyx thanks so much for your thoughtful, in depth reply. Even though I've been using the free version for quite sometime, I'd happily support purchasing the plugin if it helps enable you all to put resources towards developing it further. Other than the one issue I'm having, I have found it to be very stable, versatile and easy to use. Hit me up if you want a testimonial as we use SATT extensively through out our website. 
Randall

**Comment by franticpsyx** [comment]
You rock @dss-rtm -- @thenbrent or I will keep everyone is this repository updated once we've got something finalized.
