### ISSUE TITLE
Support Type: Product Bundles - Pull in the regular price and sale price from a variable product

### ISSUE THREAD

**Issue by seb86** [Prospress/woocommerce-subscribe-all-the-things#38]
@thenbrent, @franticpsyx I have a possible client that would like the "Regular Price" and "Sale Price" to be pulled from the relevant "Variable Product" which then affects the subscription price.

I have not yet checked but is this possible already and if not, is it something we could add?

**Comment by franticpsyx** [comment]
@seb86 Feel free to have a look at the `issue-20` branch. It's still work-in-progress, but basic Variable Products support should work without issues. I'm recommending having a look at `issue-20` instead of `master` since I've made some slight architectural changes needed to support complex product types.

**Comment by seb86** [comment]
@franticpsyx OK. That sounds great.

**Comment by franticpsyx** [comment]
Merged `issue-20` into master - CP and PB releases required to test `master` for compat are on the way later today / tomorrow.
