### ISSUE TITLE
Shipping duplicated

### ISSUE THREAD

**Issue by alextovey** [Prospress/woocommerce-subscribe-all-the-things#385]
Good morning. Shipping seems to be duplicated per product on subscription on the cart.
![shipping](https://user-images.githubusercontent.com/22075161/48341945-51e7d280-e666-11e8-896d-78b9cb12de43.gif)

**Comment by thenbrent** [comment]
Hi @alextovey, when the recurring package contents is different to the initial cart contents, shipping selection fields are displayed for each recurring cart. This is intended, because it is necessary for shipping to be calculated correctly for all packages, and it also allow customers to choose between different shipping options for different packages/orders.

In the gif you provided, there are shipping selection sections show for:

1. the initial order, containing both products
2. the weekly subscription orders, for the `Smoke TVF 12` product
3. the fortnightly subscription orders, for the `Rhubarb & Custard` product

**Comment by alextovey** [comment]
@thenbrent Oh okay, thank you. Makes sense now. Was just confusing at first.
