### ISSUE TITLE
Potential bug found - abandoned cart - when customer goes back to pay, creates additional products in cart

### ISSUE THREAD

**Issue by pinical** [Prospress/woocommerce-subscribe-all-the-things#40]
I have a scenario where I am entering in manual orders for customers who have come into a winery and want to join a wine club which I have set up as a subscription product for a composite product using this "Subscribe all the things" mini extension.

They pay for the first wine cub order through the til at the winery, and later have to be added to the website. In order to get around the fact that they have already paid for their order, but wanting to capture their payment details, I put in the order and then apply a 100% coupon discount which makes the order total zero.

At this stage, we proceed to the credit card payment details. Unfortunately my client did not capture the three digit code at the back of the credit card, so instead, we abandon the cart at this stage, and send the client an email, asking them to login and complete their payment details.

This works well on the my account page - it shows a pending order of zero dollars and gives them a "pay" button. The problem happens when they hit the pay button - instead of just seeing the composite product that was set up as a subscription and having an order total of zero, new products are added to the order (as per the screen shot).
https://www.dropbox.com/s/92yeft231yth3u7/CC%20Estate%20-%20My%20Account%20with%20Pending%20Payment.png?dl=0

https://www.dropbox.com/s/84xj8s0b9xt0nds/CC%20Estate%20-%20After%20Clicking%20Pay%20Button.png?dl=0

I did create a ticket at woothemes (ticket id 425975) with login credentials but they suggested I submit my bug here.

**Comment by franticpsyx** [comment]
>they suggested I submit my bug here

@pinical Thank you for reporting this! I hope this is not happening on a live website, though. As mentioned in all resources linking to this repository/plugin (such as https://docs.woothemes.com/document/composite-products/composite-products-mini-extensions/) Subscribe All the Things is an experimental plugin that should be considered as beta and not relied upon for production / live websites, for obvious reasons. Also, Composite Products itself is listed as officially not compatible with WooCommerce Subscriptions at https://docs.woothemes.com/document/composite-products/composite-products-extensions-compatibility/

@thenbrent Probably related to https://github.com/Prospress/woocommerce-subscriptions/issues/1362 . It is resolved in the current version of Product Bundles, but there is no fix for that in Composites since Composites technically do not support Subscription products at all.

This means CP will need to include some Subs compat code in order to have this fixed, while not officially supporting Subs.

**Comment by franticpsyx** [comment]
Fixed in CP v3.6.6, pending release.

@thenbrent I've noticed that when attempting to pay for a SATT product order that was left pending, the satt product is no longer converted to a subscription and any price overrides are lost (of course).

So we probably need to add some SATT-related order item data when creating the order, and use it to convert the (re-populated) cart items back to their initial state.

I'm not sure how WC Subs handle this internally, but I've noticed that when paying for a pending order that contains a Subscription product, the initial Subscription created with the initial (pending) order is replaced by a new one and the old Subscription is deleted/lost.

Not sure if there's anything we need to consider here.

**Comment by franticpsyx** [comment]
>So we probably need to add some SATT-related order item data when creating the order, and use it to convert the (re-populated) cart items back to their initial state.

Solved in https://github.com/Prospress/woocommerce-subscribe-all-the-things/pull/69
