### ISSUE TITLE
Recurring order never goes to processing, shows as pending payment.

### ISSUE THREAD

**Issue by gabrielacschimidt** [Prospress/woocommerce-subscribe-all-the-things#416]
<img width="1086" alt="screen shot 2019-01-29 at 7 43 40 pm" src="https://user-images.githubusercontent.com/14190418/52078749-1d0b5d80-257b-11e9-88cf-f607ce8b6515.png">

I am not sure this is a bug or a compatibility issue. I am using NMI payment processor and I created a test product that would be recurring every day. The original order worked correctly and it hit the payment processor, showing as processing immediately. The first automated order has the pending payment status and did not hit the payment processor, plus there were no automated orders after it.

Is there a log I can check or any other way I can debug this to evaluate if this is a problem with recurring payments on my processor or if there is something wrong while setting up this plugin on my store?

Is the default behavior of the orders to stop being recurring if one of them remains pending?

Thanks!

**Comment by thenbrent** [comment]
> The first automated order has the pending payment status and did not hit the payment processor, plus there were no automated orders after it.

That usually means a fatal error occurred when attempting to process the payment. This usually relates to a bug in a 3rd party plugin or custom code.

> Is there a log I can check

Yes, check the Action Scheduler logs. Info on how to find those here: https://actionscheduler.org/admin/

Hopefully, you'll see a _Failed_ action that recorded the error.

This issue isn't _Subscribe All the Things_ specific, and instead relates to the main Subscriptions plugin and your payment gateway extension. This repository is for issues with _Subscribe All the Things_, not the main _Subscriptions_ plugin or any other plugin sold via WooCommerce.com.

If the above is not sufficient, to get help debugging this issue further, please submit a ticket to WooCommerce.com support system here: http://woocommerce.com/my-account/create-a-ticket/

So that we can help as quickly as possible, please include on the WooCommerce.com ticket:

* temporary admin credentials to login to your site so we can confirm
* a copy of your System Status report

Then we can dive in to investigate it further. I'll close this one here now.
