### ISSUE TITLE
Customer Payment Page for Parent Order doesn't seem to work

### ISSUE THREAD

**Issue by sauls123** [Prospress/woocommerce-subscribe-all-the-things#417]
Hi,

I've noticed an issue where a customer cannot pay for a parent order, for a manually created subscription (https://docs.woocommerce.com/document/subscriptions/add-or-modify-a-subscription/#section-14).

1) Create a variable product, with SAAT Options (I'm using synchronised renewals) - https://nimb.ws/srGjR9
2) Navigate to **WooCommerce > Subscription >** Add New, setup a new subscription, with the new SAAT product, set the frequency to 'Every week' (to match a frequency)
3) Create the subscription and generate parent pending order (https://nimb.ws/FMWwGU)
4) Open the Parent Order, and click on the customer payment page

**Actual Result:**
User is shown an error: "Test SAAT Product is only available with a subscription plan."

![image](https://user-images.githubusercontent.com/18104815/52246987-e9646680-28df-11e9-853f-7a6822b43a9a.png)

**Expected Result:**
- I'd expected the customer to see the regular order payment page (as though it were a regular order, or a regular subscription without the SAAT scheme), which upon successful payment would activate the new subscription. 

I have seen #333, which seems quite similar (in context of 're-subscribing'), but I'm not sure if they're related in anyway, as this is for the creation of a new subscription, without the cancellation (step 5 on #333 ).

**Comment by franticpsyx** [comment]
Hey @sauls123 

You are right -- the two issues are very similar in nature.

Because the subscription was created manually, SATT can't immediately tell which plan to "activate" on that product. It needs to be manually instructed to find a matching plan from the subscription details.

We recently added a filter to the extension to customize this behavior -- could you please download and install the latest development version from the `issue-417` [branch](https://github.com/Prospress/woocommerce-subscribe-all-the-things/tree/issue-417)? 

Then, activate this snippet:

```
add_filter( 'wcsatt_restore_subscription_scheme_from_subscription_args', 'wcsatt_restore_subscription_scheme_from_subscription_args', 10 );

function wcsatt_restore_subscription_scheme_from_subscription_args( $args ) {

	if ( ! empty( $args[ 'order' ] ) && is_object( $args[ 'order' ] ) && is_a( $args[ 'order' ], 'WC_Abstract_Order' ) ) {

		if ( 'shop_subscription' === $args[ 'order' ]->get_type() ) {

			$args[ 'match_subscription' ] = $args[ 'order' ];

		} elseif ( 'shop_order' === $args[ 'order' ]->get_type() ) {

			$subscriptions = wcs_get_subscriptions_for_order( $args[ 'order' ], array(
				'order_type' => array( 'parent' )
			) );

			if ( ! empty( $subscriptions ) && sizeof( $subscriptions ) === 1 ) {
				$args[ 'match_subscription' ] = current( $subscriptions );
			}
		}
	}

	return $args;
}
```

This will allow SATT to "find" the correct subscription plan to apply on the cart item from the details of the subscription associated with the parent order you created.

**Comment by sauls123** [comment]
Thanks @franticpsyx , this works perfectly now :)
