### ISSUE TITLE
Subscription Total text not formatting correctly

### ISSUE THREAD

**Issue by HQadmin007** [Prospress/woocommerce-subscribe-all-the-things#419]
Hello, I have noticed an issue when viewing 'Subscription Totals'. 

If you click 'My account' then click 'Subscriptions' then 'view' any subscription. we have noticed that the below is happening.

Any help would be much appreciated! 😸 

![image of issue](https://user-images.githubusercontent.com/46896605/52284725-df347d80-295c-11e9-8ba7-25d68a778b80.JPG)

**Comment by franticpsyx** [comment]
Hey @HQadmin007 -- it's not clear to us how that meta data got stored in the Subscription order. Composite Products is adding that metadata in the mini-cart template.

This is most likely caused by either:

<ul>
<li>custom code, such as snippets and overridden templates;</li>
<li>a conflict with your theme; or</li>
<li>a conflict with another plugin.</li>
</ul>

Here's how we usually investigate such issues:

<ol>
<li>Temporarily switch back to a default WordPress theme (or Storefront) and create a new, identical subscription. If this resolves the issue, then please bring this to the attention of your theme author.</li>
<li>If the issue persists, then disable all other plugins except for WooCommerce, WCS and SATT -- and then create a new, identical subscription. Did the issue persist?</li>
</ol>
