### ISSUE TITLE
Apply to all

### ISSUE THREAD

**Issue by madmayweb** [Prospress/woocommerce-subscribe-all-the-things#430]
Hey! This is AWESOME! What would be the easiest way to apply the same options to all products? we have over 20,000

**Comment by mfahad19** [comment]
We have to apply it to 5000+ products, hope there is a easy solution for this.

**Comment by franticpsyx** [comment]
Hey there,

There are two options:

1. Set up **cart subscription schemes** from **WooCommerce > Settings > Subscriptions** instead of adding the same plans to every product. This is somewhat limiting, because cart subscriptions prevent you from adding multiple products with different plans in the same cart.

2. Use the **WooCommerce REST API** or **Product Importer** to save your subscription plans/settings configuration on multiple products. List of product meta to look up:

* `_wcsatt_schemes`
* `_wcsatt_force_subscription`
* `_wcsatt_default_status`
* `_wcsatt_subscription_prompt`

**Comment by madmayweb** [comment]
Awesome thank for the response! I was able to update using a mass edit plugin (advanced_bulk_edit) and added _wcsatt_schemes with what I needed which was: 

a:3:{i:0;a:10:{s:28:"subscription_period_interval";s:1:"1";s:19:"subscription_period";s:5:"month";s:19:"subscription_length";s:1:"0";s:27:"subscription_pricing_method";s:7:"inherit";s:26:"subscription_regular_price";s:0:"";s:23:"subscription_sale_price";s:0:"";s:21:"subscription_discount";s:0:"";s:8:"position";s:1:"0";s:18:"subscription_price";s:0:"";s:30:"subscription_payment_sync_date";i:0;}i:1;a:10:{s:28:"subscription_period_interval";s:1:"2";s:19:"subscription_period";s:5:"month";s:19:"subscription_length";s:1:"0";s:27:"subscription_pricing_method";s:7:"inherit";s:26:"subscription_regular_price";s:0:"";s:23:"subscription_sale_price";s:0:"";s:21:"subscription_discount";s:0:"";s:8:"position";s:1:"1";s:18:"subscription_price";s:0:"";s:30:"subscription_payment_sync_date";i:0;}i:2;a:10:{s:28:"subscription_period_interval";s:1:"3";s:19:"subscription_period";s:5:"month";s:19:"subscription_length";s:1:"0";s:27:"subscription_pricing_method";s:7:"inherit";s:26:"subscription_regular_price";s:0:"";s:23:"subscription_sale_price";s:0:"";s:21:"subscription_discount";s:0:"";s:8:"position";s:1:"2";s:18:"subscription_price";s:0:"";s:30:"subscription_payment_sync_date";i:0;}}

Thanks again for your quick response!
