### ISSUE TITLE
Don't trigger 'woocommerce-product-type-change' JS event every time users add a subscription scheme 

### ISSUE THREAD

**Issue by thenbrent** [Prospress/woocommerce-subscribe-all-the-things#64]
SATT currently triggers `woocommerce-product-type-change` every time users add a subscription scheme to a simple product here: https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/aeb6756d/assets/js/wcsatt-write-panels.js#L198

The product type doesn't change every time a new subscription scheme changes.

It only changes when the first scheme is added, or when the last scheme is removed.

SATT should only trigger `woocommerce-product-type-change` on those events.

SATT might also need to stop WooCommerce & Subscriptions from changing the focused tab on this event, because it's uses it in a different way to the normal product change behaviour and we don't really want to change the focus from the Subscriptions tab.

**Comment by franticpsyx** [comment]
I don't see any need to trigger `woocommerce-product-type-change` in there at all, but I don't see why triggering this event one or a thousand times should have anything to do with other plugins/extensions. This is not the real bug here. 

The real issue is that the One Time Shipping logic just doesn't work:

https://cl.ly/1d033Q3p1315

The script merged to support the "One Time Shipping" option in https://github.com/Prospress/woocommerce-subscribe-all-the-things/pull/54 has some issues. This should take care of it, hopefully: https://github.com/Prospress/woocommerce-subscribe-all-the-things/commit/c8215bf3233ae4277b95197bb1e49ed3a20ea3ce
