### ISSUE TITLE
Dynamic Pricing Plugin not compatible

### ISSUE THREAD

**Issue by martinmansson** [Prospress/woocommerce-subscribe-all-the-things#90]
Hi there,

When adding a subscription on product level the cart gets messed up when the Dynamic Pricing plugin is active. See image.

![screen shot 2016-12-22 at 10 57 38](https://cloud.githubusercontent.com/assets/779205/21421905/8014fe68-c835-11e6-8755-e9a013b14edb.png)

When disabled it works like a charm.

![screen shot 2016-12-22 at 10 58 31](https://cloud.githubusercontent.com/assets/779205/21421929/9aab75d6-c835-11e6-8346-1cee333a1f03.png)

Subscribe to cart works with the plugin activated if no product is added to the cart with subscription enabled on product level.

![screen shot 2016-12-22 at 10 59 34](https://cloud.githubusercontent.com/assets/779205/21421967/d7dc82b0-c835-11e6-9edf-202352d2d679.png)

Guess its some conflict with the discount on product subscription and dynamic pricing plugin.

Best,
Martin

**Comment by franticpsyx** [comment]
Thanks for the report @martinmansson 

At the moment we have no plans to support any other plugins other than WC Subscriptions and the product-types (and associated extensions) mentioned in the repo description (readme).

Long-term, we intend to support other official plugins but only after implementing all features planned for the list of plugins targeted by SATT since v1.

I would normally leave this open since it's on our radar, but it's such a long-term goal that it makes little sense to leave a ticket open for every official extension unsupported by SATT. We will be revising our roadmap as we work on (and deliver) new features, so I am certain this will be revisited.
