### ISSUE TITLE
Add to cart does not work

### ISSUE THREAD

**Issue by dutchandyoung** [Prospress/woocommerce-subscribe-all-the-things#92]
Hi,

When i add a simple product with (forced subscription) to the cart with php ?add-to-cart=id
The product will be added to the cart and will display it as a subscription, but when i go to the product detail page and add it (single-product.php) then it will be added as a normal product in the cart?

Whats happening here?

**Comment by franticpsyx** [comment]
Hey @dutchandyoung -- I am not able to replicate this one. The only issue I see is that when the product is added to the cart using the query-string method it appears as a new cart item, instead of increasing the quantity of an existing one added by clicking "Sign Up Now":

https://cl.ly/3B0K0H2H4314
